import { Link } from "@tanstack/react-router";
import { ArrowLeft, LayoutDashboard, Search, ShoppingBag } from "lucide-react";
import type { ReactNode } from "react";
import { cartCount, useCart } from "@/lib/shop-cart";

export function ShopShell({ children }: { children: ReactNode }) {
  const cart = useCart();
  const count = cartCount(cart);

  return (
    <div className="min-h-dvh bg-background">
      <a
        href="#shop-main"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-primary focus:px-3 focus:py-2 focus:text-primary-foreground"
      >
        Skip to content
      </a>
      <header className="sticky top-0 z-40 border-b border-border bg-background/85 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-5">
          <div className="flex items-center gap-2">
            <Link to="/shop" className="text-sm font-semibold tracking-tight">
              Kadam Athletics
            </Link>
            <span className="rounded-full border border-border px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
              Storefront Demo
            </span>
          </div>
          <nav className="flex items-center gap-1 text-sm" aria-label="Storefront">
            <Link
              to="/shop/search"
              className="link-sweep inline-flex items-center gap-1.5 rounded-md px-3 py-2 text-muted-foreground hover:text-foreground"
            >
              <Search className="size-4" aria-hidden /> Search
            </Link>
            <Link
              to="/shop/cart"
              className="press inline-flex items-center gap-2 rounded-md border border-border px-3 py-2"
            >
              <ShoppingBag className="size-4" aria-hidden />
              Cart
              <span className="tabular rounded-full bg-primary px-1.5 text-[11px] text-primary-foreground">
                {count}
              </span>
            </Link>
            <Link
              to="/dashboard"
              className="link-sweep ml-1 inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-2 text-muted-foreground hover:text-foreground"
            >
              <LayoutDashboard className="size-4" aria-hidden /> Merchant cockpit
            </Link>
          </nav>
        </div>
      </header>
      <main id="shop-main" className="mx-auto max-w-6xl px-5 py-10">
        {children}
      </main>
      <footer className="border-t border-border">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-6 text-xs text-muted-foreground">
          <p>Shopper view — recommendations on this store are generated by Sarthi.</p>
          <Link
            to="/"
            className="link-sweep inline-flex items-center gap-1.5 hover:text-foreground"
          >
            <ArrowLeft className="size-3.5" aria-hidden /> Back to Sarthi
          </Link>
        </div>
      </footer>
    </div>
  );
}

export function ProductArt({ hue, className }: { hue: number; className?: string }) {
  return (
    <div
      className={className ?? "aspect-[4/3] w-full rounded-lg"}
      style={{
        background: `linear-gradient(140deg, oklch(0.9 0.06 ${hue}), oklch(0.78 0.1 ${(hue + 40) % 360}))`,
      }}
      aria-hidden
    />
  );
}
