/**
 * Small, hand-authored example payloads.
 * Not a synthetic data generator — just enough for every screen to be legible.
 */
import type {
  AuditEvent,
  AgentAction,
  Campaign,
  Cart,
  Customer,
  DashboardSummary,
  Experiment,
  Merchant,
  Opportunity,
  Order,
  Policy,
  Product,
  Recommendation,
  RecoveryCase,
} from "@/lib/types";

export const merchant: Merchant = {
  id: "mch_01",
  name: "Kadam Athletics",
  storeUrl: "kadam.store",
  currency: "INR",
  plan: "scale",
  razorpayConnected: true,
  testMode: true,
  createdAt: "2026-02-11T09:00:00Z",
};

export const products: Product[] = [
  {
    id: "prd_runner",
    sku: "KA-RUN-01",
    name: "Trailhead Running Shoe",
    category: "Footwear",
    price: 6499,
    compareAtPrice: 7999,
    inventory: 128,
    unitsSold30d: 412,
    conversionRate: 0.041,
    aovContribution: 0.22,
    crossSellOpportunities: 3,
    aiScore: 92,
    rating: 4.6,
    imageHue: 62,
    status: "active",
  },
  {
    id: "prd_socks",
    sku: "KA-SOC-04",
    name: "Merino Cushion Socks (3 pack)",
    category: "Accessories",
    price: 899,
    inventory: 640,
    unitsSold30d: 908,
    conversionRate: 0.078,
    aovContribution: 0.06,
    crossSellOpportunities: 5,
    aiScore: 88,
    rating: 4.4,
    imageHue: 172,
    status: "active",
  },
  {
    id: "prd_tee",
    sku: "KA-TEE-11",
    name: "Airflow Training Tee",
    category: "Apparel",
    price: 1799,
    inventory: 42,
    unitsSold30d: 264,
    conversionRate: 0.033,
    aovContribution: 0.09,
    crossSellOpportunities: 2,
    aiScore: 74,
    rating: 4.2,
    imageHue: 232,
    status: "low_stock",
  },
  {
    id: "prd_bottle",
    sku: "KA-BTL-02",
    name: "Insulated Sport Bottle 750ml",
    category: "Accessories",
    price: 1299,
    inventory: 0,
    unitsSold30d: 187,
    conversionRate: 0.052,
    aovContribution: 0.04,
    crossSellOpportunities: 4,
    aiScore: 69,
    rating: 4.5,
    imageHue: 82,
    status: "out_of_stock",
  },
  {
    id: "prd_band",
    sku: "KA-BND-07",
    name: "Resistance Band Set",
    category: "Training",
    price: 1499,
    inventory: 310,
    unitsSold30d: 96,
    conversionRate: 0.019,
    aovContribution: 0.03,
    crossSellOpportunities: 1,
    aiScore: 51,
    rating: 4.1,
    imageHue: 330,
    status: "active",
  },
  {
    id: "prd_jacket",
    sku: "KA-JKT-03",
    name: "Windshell Running Jacket",
    category: "Apparel",
    price: 4299,
    compareAtPrice: 4999,
    inventory: 76,
    unitsSold30d: 121,
    conversionRate: 0.027,
    aovContribution: 0.12,
    crossSellOpportunities: 3,
    aiScore: 81,
    rating: 4.7,
    imageHue: 210,
    status: "active",
  },
];

const trend = [
  { date: "Aug 01", revenue: 412000, aiRevenue: 61000, orders: 214, aov: 1925, conversion: 2.4 },
  { date: "Aug 05", revenue: 448000, aiRevenue: 72000, orders: 231, aov: 1939, conversion: 2.5 },
  { date: "Aug 09", revenue: 396000, aiRevenue: 68000, orders: 205, aov: 1932, conversion: 2.3 },
  { date: "Aug 13", revenue: 501000, aiRevenue: 96000, orders: 249, aov: 2012, conversion: 2.7 },
  { date: "Aug 17", revenue: 538000, aiRevenue: 118000, orders: 262, aov: 2053, conversion: 2.9 },
  { date: "Aug 21", revenue: 496000, aiRevenue: 109000, orders: 240, aov: 2066, conversion: 2.8 },
  { date: "Aug 25", revenue: 604000, aiRevenue: 151000, orders: 283, aov: 2134, conversion: 3.1 },
];

export const dashboard: DashboardSummary = {
  totalRevenue: 3395000,
  aiAttributedRevenue: 675000,
  recoveredRevenue: 214000,
  incrementalRevenue: 288000,
  aov: 2134,
  conversionRate: 3.1,
  acceptanceRate: 0.72,
  deltas: {
    totalRevenue: 12.4,
    aiAttributedRevenue: 31.8,
    recoveredRevenue: 18.2,
    incrementalRevenue: 9.6,
    aov: 4.1,
    conversionRate: 0.4,
    acceptanceRate: 6.0,
  },
  trend,
  attribution: [
    { source: "cross_sell", label: "Cross-sell & bundles", revenue: 268000, deltaPct: 22.1 },
    { source: "recovery", label: "Recovery workflows", revenue: 214000, deltaPct: 18.2 },
    { source: "upsell", label: "Upsell", revenue: 121000, deltaPct: 7.4 },
    { source: "campaign", label: "Approved campaigns", revenue: 72000, deltaPct: -3.2 },
  ],
};

const bundleActions: AgentAction[] = [
  {
    id: "act_1",
    agent: "Growth Analyst",
    action: "Detected co-purchase pattern",
    detail: "Trailhead Running Shoe + Merino Cushion Socks co-purchased in 38% of orders.",
    status: "completed",
    at: "2026-08-26T06:12:00Z",
    correlationId: "corr_9f21",
  },
  {
    id: "act_2",
    agent: "Recommendation Engine",
    action: "Drafted bundle proposal",
    detail: "Bundle at ₹6,999 with 6% effective discount.",
    status: "completed",
    at: "2026-08-26T06:12:40Z",
    correlationId: "corr_9f21",
  },
  {
    id: "act_3",
    agent: "Policy Engine",
    action: "Policy evaluation",
    detail: "Discount 6% within 15% cap. Category allowed. Requires merchant approval.",
    status: "completed",
    at: "2026-08-26T06:12:44Z",
    correlationId: "corr_9f21",
  },
  {
    id: "act_4",
    agent: "Merchant Approval",
    action: "Awaiting decision",
    detail: "Proposal queued for merchant review.",
    status: "awaiting_approval",
    at: "2026-08-26T06:13:00Z",
    correlationId: "corr_9f21",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "opp_bundle_shoe_socks",
    title: "Bundle Trailhead Shoe with Merino Socks",
    type: "bundle",
    status: "new",
    expectedRevenue: 184000,
    expectedOrders: 96,
    confidence: 0.86,
    confidenceIntervalLow: 142000,
    confidenceIntervalHigh: 221000,
    summary:
      "Shoppers who buy the Trailhead Running Shoe buy socks separately within 9 days in a third of cases. A bundle captures that second purchase at the first checkout.",
    rationale:
      "Co-purchase affinity is high and the socks carry healthy margin, so a modest bundle discount stays inside the configured discount ceiling.",
    evidence: [
      {
        kind: "observed",
        statement: "38% of Trailhead Shoe orders include Merino Socks in the same session.",
        metric: "412 orders / 30 days",
        source: "Order history",
      },
      {
        kind: "observed",
        statement: "A further 31% purchase socks separately within 9 days.",
        metric: "median 9 days",
        source: "Customer purchase sequence",
      },
      {
        kind: "observed",
        statement: "Socks inventory at 640 units covers 21 days of bundled demand.",
        metric: "640 units",
        source: "Inventory snapshot",
      },
      {
        kind: "recommendation",
        statement: "Offer a shoe + socks bundle at ₹6,999 on product and cart surfaces.",
        source: "Recommendation Engine",
      },
    ],
    affectedProductIds: ["prd_runner", "prd_socks"],
    segment: "Footwear buyers, all segments",
    segmentSize: 4120,
    risk: "low",
    riskNotes:
      "Bundle discount reduces socks margin by 4 points; no inventory risk at current cover.",
    policyChecks: [
      { policy: "Max discount 15%", result: "pass", detail: "Effective discount 6%." },
      {
        policy: "Allowed categories",
        result: "pass",
        detail: "Footwear and Accessories are allowed.",
      },
      {
        policy: "Merchant approval for pricing changes",
        result: "requires_approval",
        detail: "Pricing actions always need approval.",
      },
    ],
    recommendedAction:
      "Publish bundle offer on PDP, cart and Sarthi storefront recommendations for 21 days.",
    simulation: [
      { scenario: "Conservative", orders: 62, revenue: 118000 },
      { scenario: "Expected", orders: 96, revenue: 184000 },
      { scenario: "Optimistic", orders: 124, revenue: 238000 },
    ],
    discoveredAt: "2026-08-26T06:12:00Z",
    executionHistory: bundleActions,
  },
  {
    id: "opp_payment_retry_upi",
    title: "Recover failed UPI payments with a timed retry",
    type: "payment_recovery",
    status: "approved",
    expectedRevenue: 96000,
    expectedOrders: 48,
    confidence: 0.79,
    confidenceIntervalLow: 71000,
    confidenceIntervalHigh: 119000,
    summary:
      "UPI collect requests are failing on timeout for a specific bank handle. Retrying after 12 minutes with an alternate method recovers a large share of them.",
    rationale:
      "Failure reason is transient, so a bounded retry with one alternate method is low risk.",
    evidence: [
      {
        kind: "observed",
        statement: "126 UPI payments failed with a collect timeout in 30 days.",
        metric: "₹243,000 at risk",
        source: "Payments",
      },
      {
        kind: "observed",
        statement: "Retries within 15 minutes succeed 41% of the time.",
        metric: "41% success",
        source: "Recovery history",
      },
      {
        kind: "recommendation",
        statement: "Send one retry link 12 minutes after failure with card fallback.",
        source: "Recovery Agent",
      },
    ],
    affectedProductIds: ["prd_runner", "prd_jacket"],
    segment: "Shoppers with a failed payment in the last 24h",
    segmentSize: 126,
    risk: "low",
    riskNotes: "One message per customer; duplicate-charge prevention enforced at checkout.",
    policyChecks: [
      {
        policy: "Customer communication",
        result: "pass",
        detail: "Transactional message, within 1 per order.",
      },
      {
        policy: "Payment permissions",
        result: "pass",
        detail: "Retry link only; no charge initiated by agent.",
      },
    ],
    recommendedAction: "Enable timed retry workflow for UPI timeout failures.",
    simulation: [
      { scenario: "Conservative", orders: 31, revenue: 64000 },
      { scenario: "Expected", orders: 48, revenue: 96000 },
      { scenario: "Optimistic", orders: 59, revenue: 121000 },
    ],
    discoveredAt: "2026-08-24T11:40:00Z",
    executionHistory: [
      {
        id: "act_5",
        agent: "Recovery Agent",
        action: "Workflow enabled",
        detail: "Timed retry live for UPI timeout failures.",
        status: "completed",
        at: "2026-08-24T12:05:00Z",
        correlationId: "corr_4b77",
      },
    ],
    outcome: {
      revenue: 87400,
      orders: 43,
      incremental: 61200,
      note: "43 of 126 failed payments recovered in 14 days.",
    },
  },
  {
    id: "opp_inventory_tee",
    title: "Slow down Airflow Tee promotion — inventory cover is 5 days",
    type: "inventory_promo",
    status: "blocked",
    expectedRevenue: 0,
    expectedOrders: 0,
    confidence: 0.68,
    confidenceIntervalLow: 0,
    confidenceIntervalHigh: 0,
    summary:
      "A proposed 25% promotion on the Airflow Training Tee exceeds the merchant discount ceiling and would exhaust stock before restock.",
    rationale: "Demand at the proposed price outpaces the 42 units on hand.",
    evidence: [
      {
        kind: "observed",
        statement: "Airflow Tee inventory is 42 units, roughly 5 days of cover.",
        metric: "42 units",
        source: "Inventory",
      },
      {
        kind: "observed",
        statement: "Proposed discount of 25% exceeds the 15% policy ceiling.",
        metric: "25% vs 15%",
        source: "Policy Engine",
      },
      {
        kind: "recommendation",
        statement: "Hold promotion until restock; cap discount at 15%.",
        source: "Policy Engine",
      },
    ],
    affectedProductIds: ["prd_tee"],
    segment: "Apparel browsers",
    segmentSize: 2210,
    risk: "high",
    riskNotes: "Stock-out risk plus policy breach.",
    policyChecks: [
      { policy: "Max discount 15%", result: "block", detail: "Requested 25% exceeds ceiling." },
      { policy: "Inventory floor", result: "block", detail: "Would breach 20-unit safety stock." },
    ],
    recommendedAction: "Blocked. Re-propose after restock with a compliant discount.",
    simulation: [{ scenario: "Blocked", orders: 0, revenue: 0 }],
    discoveredAt: "2026-08-25T08:02:00Z",
    executionHistory: [
      {
        id: "act_6",
        agent: "Policy Engine",
        action: "Action blocked",
        detail: "Discount 25% exceeds configured maximum of 15%.",
        status: "blocked",
        at: "2026-08-25T08:02:30Z",
        correlationId: "corr_1c03",
      },
    ],
  },
  {
    id: "opp_cart_recovery",
    title: "Recover high-value abandoned carts within 90 minutes",
    type: "cart_recovery",
    status: "under_review",
    expectedRevenue: 142000,
    expectedOrders: 64,
    confidence: 0.74,
    confidenceIntervalLow: 98000,
    confidenceIntervalHigh: 176000,
    summary:
      "Carts above ₹3,000 abandoned at the shipping step recover well with a single reminder and no discount.",
    rationale: "Recovery lift is driven by timing, not discounting, so margin is preserved.",
    evidence: [
      {
        kind: "observed",
        statement: "218 carts above ₹3,000 abandoned at shipping in 30 days.",
        metric: "₹812,000 at risk",
        source: "Carts",
      },
      {
        kind: "observed",
        statement: "Reminders sent within 90 minutes convert 2.3x better than 24h reminders.",
        source: "Recovery history",
      },
      {
        kind: "recommendation",
        statement: "Send one no-discount reminder 90 minutes after abandonment.",
        source: "Recovery Agent",
      },
    ],
    affectedProductIds: ["prd_runner", "prd_jacket", "prd_bottle"],
    segment: "High-value abandoners",
    segmentSize: 218,
    risk: "medium",
    riskNotes: "Message volume must stay inside communication caps.",
    policyChecks: [
      {
        policy: "Customer communication",
        result: "pass",
        detail: "1 message per cart, inside daily cap.",
      },
      {
        policy: "Max actions per hour",
        result: "requires_approval",
        detail: "Peak volume may reach 80/hour vs 50 configured.",
      },
    ],
    recommendedAction: "Approve with an hourly send cap of 50.",
    simulation: [
      { scenario: "Conservative", orders: 41, revenue: 92000 },
      { scenario: "Expected", orders: 64, revenue: 142000 },
      { scenario: "Optimistic", orders: 78, revenue: 174000 },
    ],
    discoveredAt: "2026-08-26T04:31:00Z",
    executionHistory: [],
  },
  {
    id: "opp_upsell_jacket",
    title: "Upsell Windshell Jacket to repeat shoe buyers",
    type: "upsell",
    status: "executed",
    expectedRevenue: 88000,
    expectedOrders: 21,
    confidence: 0.71,
    confidenceIntervalLow: 60000,
    confidenceIntervalHigh: 108000,
    summary:
      "Repeat footwear buyers convert on outerwear at 3x the site average when shown after a second order.",
    rationale:
      "Post-purchase placement avoids discounting and reaches an already-converted audience.",
    evidence: [
      {
        kind: "observed",
        statement: "Repeat buyers convert on Windshell Jacket at 6.2% post-purchase.",
        source: "Recommendations",
      },
      {
        kind: "recommendation",
        statement: "Show jacket on order confirmation for repeat footwear buyers.",
        source: "Recommendation Engine",
      },
    ],
    affectedProductIds: ["prd_jacket", "prd_runner"],
    segment: "Repeat footwear buyers",
    segmentSize: 690,
    risk: "low",
    riskNotes: "No pricing change involved.",
    policyChecks: [
      {
        policy: "Merchant approval for new surfaces",
        result: "pass",
        detail: "Approved on 20 Aug.",
      },
    ],
    recommendedAction: "Keep running; review attach rate weekly.",
    simulation: [{ scenario: "Expected", orders: 21, revenue: 88000 }],
    discoveredAt: "2026-08-18T07:20:00Z",
    executionHistory: [
      {
        id: "act_7",
        agent: "Campaign Executor",
        action: "Surface enabled",
        detail: "Post-purchase upsell live on order confirmation.",
        status: "completed",
        at: "2026-08-20T09:10:00Z",
        correlationId: "corr_77aa",
      },
    ],
    outcome: {
      revenue: 94300,
      orders: 23,
      incremental: 71000,
      note: "Attach rate 6.4%, above the 4.5% forecast.",
    },
  },
];

export const orders: Order[] = [
  {
    id: "ord_10241",
    customerName: "Aarav Mehta",
    items: 3,
    amount: 8397,
    status: "paid",
    aiAttributed: true,
    attributionSource: "cross_sell",
    placedAt: "2026-08-26T05:41:00Z",
  },
  {
    id: "ord_10240",
    customerName: "Ishita Rao",
    items: 1,
    amount: 4299,
    status: "fulfilled",
    aiAttributed: false,
    placedAt: "2026-08-26T04:12:00Z",
  },
  {
    id: "ord_10239",
    customerName: "Kabir Shah",
    items: 2,
    amount: 7398,
    status: "failed",
    aiAttributed: false,
    placedAt: "2026-08-26T03:55:00Z",
  },
  {
    id: "ord_10238",
    customerName: "Meera Nair",
    items: 4,
    amount: 10995,
    status: "paid",
    aiAttributed: true,
    attributionSource: "recovery",
    placedAt: "2026-08-25T19:20:00Z",
  },
  {
    id: "ord_10237",
    customerName: "Dev Patel",
    items: 2,
    amount: 5198,
    status: "pending",
    aiAttributed: true,
    attributionSource: "upsell",
    placedAt: "2026-08-25T17:02:00Z",
  },
  {
    id: "ord_10236",
    customerName: "Sara Iyer",
    items: 1,
    amount: 899,
    status: "refunded",
    aiAttributed: false,
    placedAt: "2026-08-25T12:44:00Z",
  },
];

export const customers: Customer[] = [
  {
    id: "cus_01",
    name: "Aarav Mehta",
    email: "aarav@example.com",
    segment: "vip",
    orders: 14,
    lifetimeValue: 96400,
    lastOrderAt: "2026-08-26T05:41:00Z",
    aiInfluencedRevenue: 21400,
  },
  {
    id: "cus_02",
    name: "Ishita Rao",
    email: "ishita@example.com",
    segment: "returning",
    orders: 5,
    lifetimeValue: 28700,
    lastOrderAt: "2026-08-26T04:12:00Z",
    aiInfluencedRevenue: 6100,
  },
  {
    id: "cus_03",
    name: "Kabir Shah",
    email: "kabir@example.com",
    segment: "at_risk",
    orders: 2,
    lifetimeValue: 9100,
    lastOrderAt: "2026-07-02T10:00:00Z",
    aiInfluencedRevenue: 0,
  },
  {
    id: "cus_04",
    name: "Meera Nair",
    email: "meera@example.com",
    segment: "returning",
    orders: 7,
    lifetimeValue: 41200,
    lastOrderAt: "2026-08-25T19:20:00Z",
    aiInfluencedRevenue: 12800,
  },
  {
    id: "cus_05",
    name: "Dev Patel",
    email: "dev@example.com",
    segment: "new",
    orders: 1,
    lifetimeValue: 5198,
    lastOrderAt: "2026-08-25T17:02:00Z",
    aiInfluencedRevenue: 5198,
  },
];

export const carts: Cart[] = [
  {
    id: "crt_881",
    customerName: "Nikhil Verma",
    items: 3,
    value: 9297,
    state: "abandoned",
    lastActivityAt: "2026-08-26T05:10:00Z",
    recoveryAttempts: 1,
  },
  {
    id: "crt_880",
    customerName: "Priya Sen",
    items: 1,
    value: 6499,
    state: "checkout_started",
    lastActivityAt: "2026-08-26T04:58:00Z",
    recoveryAttempts: 0,
  },
  {
    id: "crt_879",
    customerName: "Rohan Das",
    items: 2,
    value: 3098,
    state: "recovered",
    lastActivityAt: "2026-08-25T21:31:00Z",
    recoveryAttempts: 2,
  },
  {
    id: "crt_878",
    customerName: "Tanvi Kulkarni",
    items: 5,
    value: 14894,
    state: "abandoned",
    lastActivityAt: "2026-08-25T18:02:00Z",
    recoveryAttempts: 0,
  },
  {
    id: "crt_877",
    customerName: "Aditya Bose",
    items: 1,
    value: 1499,
    state: "active",
    lastActivityAt: "2026-08-26T06:02:00Z",
    recoveryAttempts: 0,
  },
];

export const recoveryCases: RecoveryCase[] = [
  {
    id: "rec_01",
    kind: "payment_failure",
    customerName: "Kabir Shah",
    atRisk: 7398,
    recoverable: 5200,
    attempts: 1,
    recovered: 0,
    status: "in_progress",
    reason: "UPI collect timeout",
    at: "2026-08-26T03:55:00Z",
  },
  {
    id: "rec_02",
    kind: "payment_failure",
    customerName: "Ritika Jain",
    atRisk: 4299,
    recoverable: 4299,
    attempts: 2,
    recovered: 4299,
    status: "recovered",
    reason: "Card declined — insufficient funds",
    at: "2026-08-25T14:20:00Z",
  },
  {
    id: "rec_03",
    kind: "abandoned_cart",
    customerName: "Tanvi Kulkarni",
    atRisk: 14894,
    recoverable: 9800,
    attempts: 0,
    recovered: 0,
    status: "open",
    reason: "Abandoned at shipping step",
    at: "2026-08-25T18:02:00Z",
  },
  {
    id: "rec_04",
    kind: "abandoned_cart",
    customerName: "Rohan Das",
    atRisk: 3098,
    recoverable: 3098,
    attempts: 2,
    recovered: 3098,
    status: "recovered",
    reason: "Reminder at 90 minutes",
    at: "2026-08-25T21:31:00Z",
  },
  {
    id: "rec_05",
    kind: "incomplete_checkout",
    customerName: "Priya Sen",
    atRisk: 6499,
    recoverable: 4900,
    attempts: 1,
    recovered: 0,
    status: "in_progress",
    reason: "Address validation drop-off",
    at: "2026-08-26T04:58:00Z",
  },
];

export const recommendations: Recommendation[] = [
  {
    id: "rcm_01",
    surface: "storefront",
    type: "cross_sell",
    productName: "Merino Cushion Socks",
    category: "Accessories",
    segment: "Footwear buyers",
    impressions: 24100,
    clicks: 3120,
    addToCart: 1420,
    purchases: 612,
    attachRate: 0.196,
    revenue: 268000,
  },
  {
    id: "rcm_02",
    surface: "cart",
    type: "bundle",
    productName: "Shoe + Socks bundle",
    category: "Footwear",
    segment: "All",
    impressions: 8600,
    clicks: 1490,
    addToCart: 780,
    purchases: 341,
    attachRate: 0.229,
    revenue: 184000,
  },
  {
    id: "rcm_03",
    surface: "checkout",
    type: "upsell",
    productName: "Windshell Running Jacket",
    category: "Apparel",
    segment: "Repeat buyers",
    impressions: 5400,
    clicks: 610,
    addToCart: 288,
    purchases: 121,
    attachRate: 0.112,
    revenue: 94300,
  },
  {
    id: "rcm_04",
    surface: "email",
    type: "cart_recovery",
    productName: "Insulated Sport Bottle",
    category: "Accessories",
    segment: "Abandoners",
    impressions: 3100,
    clicks: 470,
    addToCart: 210,
    purchases: 88,
    attachRate: 0.071,
    revenue: 41000,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp_01",
    name: "Monsoon running restock",
    channel: "email",
    objective: "Reactivate lapsed footwear buyers",
    status: "live",
    budget: 60000,
    spend: 21400,
    revenue: 148000,
    audience: 4200,
    startedAt: "2026-08-18T00:00:00Z",
  },
  {
    id: "cmp_02",
    name: "Socks attach push",
    channel: "onsite",
    objective: "Raise attach rate on footwear PDPs",
    status: "live",
    budget: 20000,
    spend: 6100,
    revenue: 92000,
    audience: 12800,
    startedAt: "2026-08-21T00:00:00Z",
  },
  {
    id: "cmp_03",
    name: "Jacket pre-season",
    channel: "whatsapp",
    objective: "Warm outerwear demand",
    status: "awaiting_approval",
    budget: 45000,
    spend: 0,
    revenue: 0,
    audience: 3100,
    startedAt: "2026-08-27T00:00:00Z",
  },
  {
    id: "cmp_04",
    name: "Bottle restock alert",
    channel: "sms",
    objective: "Notify waitlist on restock",
    status: "draft",
    budget: 12000,
    spend: 0,
    revenue: 0,
    audience: 860,
    startedAt: "2026-08-29T00:00:00Z",
  },
];

export const experiments: Experiment[] = [
  {
    id: "exp_01",
    name: "Shoe + socks recommendation",
    hypothesis: "Showing socks on the shoe PDP raises attach rate without hurting conversion.",
    status: "running",
    control: {
      label: "No recommendation",
      sessions: 18400,
      conversion: 2.6,
      aov: 2011,
      attachRate: 0.04,
      revenuePerSession: 52.3,
    },
    variant: {
      label: "Sarthi cross-sell",
      sessions: 18310,
      conversion: 2.8,
      aov: 2189,
      attachRate: 0.19,
      revenuePerSession: 61.3,
    },
    lift: 17.2,
    confidence: 0.94,
    incrementalRevenue: 164000,
  },
  {
    id: "exp_02",
    name: "90-minute cart reminder",
    hypothesis: "Earlier reminders recover more carts than 24-hour reminders.",
    status: "running",
    control: {
      label: "24h reminder",
      sessions: 4100,
      conversion: 5.1,
      aov: 3120,
      attachRate: 0.0,
      revenuePerSession: 159,
    },
    variant: {
      label: "90m reminder",
      sessions: 4080,
      conversion: 8.7,
      aov: 3084,
      attachRate: 0.0,
      revenuePerSession: 268,
    },
    lift: 68.5,
    confidence: 0.98,
    incrementalRevenue: 96000,
  },
  {
    id: "exp_03",
    name: "Post-purchase jacket upsell",
    hypothesis: "Outerwear upsell after purchase lifts revenue per session for repeat buyers.",
    status: "concluded",
    control: {
      label: "Thank-you page only",
      sessions: 2600,
      conversion: 0,
      aov: 0,
      attachRate: 0.0,
      revenuePerSession: 0,
    },
    variant: {
      label: "Upsell module",
      sessions: 2580,
      conversion: 0,
      aov: 4299,
      attachRate: 0.064,
      revenuePerSession: 36.5,
    },
    lift: 6.4,
    confidence: 0.91,
    incrementalRevenue: 71000,
  },
];

export const agentActions: AgentAction[] = [
  {
    id: "aa_01",
    agent: "Growth Analyst",
    action: "Scanned 30-day order history",
    detail: "1,684 orders, 6 categories analysed for co-purchase affinity.",
    status: "completed",
    at: "2026-08-26T06:11:20Z",
    correlationId: "corr_9f21",
  },
  ...bundleActions,
  {
    id: "aa_02",
    agent: "Recovery Agent",
    action: "Queued cart reminder",
    detail: "Cart crt_881 (₹9,297) scheduled for a 90-minute reminder.",
    status: "running",
    at: "2026-08-26T06:14:10Z",
    correlationId: "corr_2d55",
  },
  {
    id: "aa_03",
    agent: "Policy Engine",
    action: "Blocked discount action",
    detail: "Airflow Tee promotion at 25% exceeds 15% ceiling.",
    status: "blocked",
    at: "2026-08-25T08:02:30Z",
    correlationId: "corr_1c03",
  },
  {
    id: "aa_04",
    agent: "Attribution Engine",
    action: "Reconciled attribution",
    detail: "₹87,400 recovered revenue attributed to UPI retry workflow.",
    status: "completed",
    at: "2026-08-25T23:00:00Z",
    correlationId: "corr_4b77",
  },
  {
    id: "aa_05",
    agent: "Campaign Executor",
    action: "Campaign pacing check",
    detail: "Monsoon restock at 36% of budget, ROAS 6.9x.",
    status: "completed",
    at: "2026-08-25T20:15:00Z",
    correlationId: "corr_88f1",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "aud_01",
    at: "2026-08-26T06:12:44Z",
    agent: "Policy Engine",
    action: "Evaluate bundle pricing proposal",
    input: "Bundle prd_runner + prd_socks at ₹6,999 (6% off)",
    decision: "Within discount ceiling; pricing change requires merchant approval",
    policyResult: "requires_approval",
    approval: "pending",
    execution: "not_executed",
    result: "Queued for merchant review",
    correlationId: "corr_9f21",
  },
  {
    id: "aud_02",
    at: "2026-08-25T08:02:30Z",
    agent: "Policy Engine",
    action: "Evaluate inventory promotion",
    input: "Discount prd_tee by 25% for 7 days",
    decision: "Blocked — requested discount exceeds configured maximum of 15%",
    policyResult: "block",
    approval: "n/a",
    execution: "not_executed",
    result: "Action blocked, merchant notified",
    correlationId: "corr_1c03",
  },
  {
    id: "aud_03",
    at: "2026-08-24T12:05:00Z",
    agent: "Recovery Agent",
    action: "Enable UPI retry workflow",
    input: "Failure reason = collect timeout, delay = 12m, fallback = card",
    decision: "Transactional message allowed; no agent-initiated charge",
    policyResult: "pass",
    approval: "merchant_approved",
    execution: "executed",
    result: "43 payments recovered (₹87,400)",
    correlationId: "corr_4b77",
  },
  {
    id: "aud_04",
    at: "2026-08-20T09:10:00Z",
    agent: "Campaign Executor",
    action: "Enable post-purchase upsell surface",
    input: "Surface = order confirmation, product = prd_jacket",
    decision: "No pricing change; inside surface permissions",
    policyResult: "pass",
    approval: "merchant_approved",
    execution: "executed",
    result: "Attach rate 6.4% over 14 days",
    correlationId: "corr_77aa",
  },
  {
    id: "aud_05",
    at: "2026-08-19T15:44:00Z",
    agent: "Campaign Executor",
    action: "Increase campaign budget",
    input: "cmp_01 budget 60,000 → 95,000",
    decision: "Blocked — exceeds max automated spend of ₹75,000",
    policyResult: "block",
    approval: "n/a",
    execution: "not_executed",
    result: "Budget unchanged",
    correlationId: "corr_88f1",
  },
];

export const policies: Policy[] = [
  {
    id: "pol_01",
    key: "max_discount",
    label: "Maximum discount",
    description: "Ceiling for any agent-proposed price reduction.",
    kind: "slider",
    value: 15,
    min: 0,
    max: 50,
    step: 1,
    unit: "%",
    group: "spend",
  },
  {
    id: "pol_02",
    key: "max_campaign_budget",
    label: "Maximum campaign budget",
    description: "Per-campaign spend limit Sarthi may propose.",
    kind: "number",
    value: 75000,
    unit: "₹",
    group: "spend",
  },
  {
    id: "pol_03",
    key: "max_automated_spend",
    label: "Maximum automated spend / month",
    description: "Total spend Sarthi may commit without a new approval.",
    kind: "number",
    value: 200000,
    unit: "₹",
    group: "spend",
  },
  {
    id: "pol_04",
    key: "approval_required_pricing",
    label: "Approval required for pricing changes",
    description: "Bundles, discounts and price tests always route to you.",
    kind: "toggle",
    value: true,
    group: "approvals",
  },
  {
    id: "pol_05",
    key: "approval_required_campaigns",
    label: "Approval required for campaigns",
    description: "New campaigns wait for merchant sign-off before launch.",
    kind: "toggle",
    value: true,
    group: "approvals",
  },
  {
    id: "pol_06",
    key: "max_actions_per_hour",
    label: "Maximum actions per hour",
    description: "Hard rate limit across all executing agents.",
    kind: "slider",
    value: 50,
    min: 5,
    max: 200,
    step: 5,
    group: "approvals",
  },
  {
    id: "pol_07",
    key: "allow_customer_messages",
    label: "Customer communication",
    description: "Allow Sarthi to send transactional recovery messages.",
    kind: "toggle",
    value: true,
    group: "communication",
  },
  {
    id: "pol_08",
    key: "max_messages_per_customer",
    label: "Messages per customer / week",
    description: "Communication frequency cap per customer.",
    kind: "slider",
    value: 3,
    min: 0,
    max: 10,
    step: 1,
    group: "communication",
  },
  {
    id: "pol_09",
    key: "allow_refunds",
    label: "Refund permissions",
    description: "Allow Sarthi to issue refunds automatically.",
    kind: "toggle",
    value: false,
    group: "payments",
  },
  {
    id: "pol_10",
    key: "allow_payment_capture",
    label: "Payment permissions",
    description: "Allow Sarthi to initiate charges. Retry links stay allowed either way.",
    kind: "toggle",
    value: false,
    group: "payments",
  },
  {
    id: "pol_11",
    key: "allowed_categories",
    label: "Allowed product categories",
    description: "Footwear, Apparel, Accessories, Training are in scope.",
    kind: "toggle",
    value: true,
    group: "catalog",
  },
  {
    id: "pol_12",
    key: "inventory_floor",
    label: "Inventory safety floor",
    description: "Sarthi will not promote below this unit count.",
    kind: "slider",
    value: 20,
    min: 0,
    max: 100,
    step: 5,
    unit: " units",
    group: "catalog",
  },
];
