/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentActivityRouteImport } from './routes/agent-activity'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CartsRouteImport } from './routes/carts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RevenueRecoveryRouteImport } from './routes/revenue-recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities/$id'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopOrderSuccessRouteImport } from './routes/shop/order-success'
import { Route as ShopSearchRouteImport } from './routes/shop/search'
import { Route as ShopProductIdRouteImport } from './routes/shop/product/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentActivityRoute = AgentActivityRouteImport.update({
  id: '/agent-activity',
  path: '/agent-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CartsRoute = CartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRecoveryRoute = RevenueRecoveryRouteImport.update({
  id: '/revenue-recovery',
  path: '/revenue-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrderSuccessRoute = ShopOrderSuccessRouteImport.update({
  id: '/shop/order-success',
  path: '/shop/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/shop/search',
  path: '/shop/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/product/$id',
  path: '/shop/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-activity': typeof AgentActivityRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/carts': typeof CartsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/experiments': typeof ExperimentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/policies': typeof PoliciesRoute
  '/recommendations': typeof RecommendationsRoute
  '/revenue-recovery': typeof RevenueRecoveryRoute
  '/settings': typeof SettingsRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop/search': typeof ShopSearchRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-activity': typeof AgentActivityRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/carts': typeof CartsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/experiments': typeof ExperimentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/policies': typeof PoliciesRoute
  '/recommendations': typeof RecommendationsRoute
  '/revenue-recovery': typeof RevenueRecoveryRoute
  '/settings': typeof SettingsRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop/search': typeof ShopSearchRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-activity': typeof AgentActivityRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/carts': typeof CartsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/experiments': typeof ExperimentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/policies': typeof PoliciesRoute
  '/recommendations': typeof RecommendationsRoute
  '/revenue-recovery': typeof RevenueRecoveryRoute
  '/settings': typeof SettingsRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop/search': typeof ShopSearchRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-activity'
    | '/ai-copilot'
    | '/analytics'
    | '/audit'
    | '/campaigns'
    | '/carts'
    | '/customers'
    | '/dashboard'
    | '/experiments'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/policies'
    | '/recommendations'
    | '/revenue-recovery'
    | '/settings'
    | '/opportunities/$id'
    | '/products/$id'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop/search'
    | '/opportunities/'
    | '/products/'
    | '/shop/'
    | '/shop/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-activity'
    | '/ai-copilot'
    | '/analytics'
    | '/audit'
    | '/campaigns'
    | '/carts'
    | '/customers'
    | '/dashboard'
    | '/experiments'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/policies'
    | '/recommendations'
    | '/revenue-recovery'
    | '/settings'
    | '/opportunities/$id'
    | '/products/$id'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop/search'
    | '/opportunities'
    | '/products'
    | '/shop'
    | '/shop/product/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-activity'
    | '/ai-copilot'
    | '/analytics'
    | '/audit'
    | '/campaigns'
    | '/carts'
    | '/customers'
    | '/dashboard'
    | '/experiments'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/policies'
    | '/recommendations'
    | '/revenue-recovery'
    | '/settings'
    | '/opportunities/$id'
    | '/products/$id'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop/search'
    | '/opportunities/'
    | '/products/'
    | '/shop/'
    | '/shop/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentActivityRoute: typeof AgentActivityRoute
  AiCopilotRoute: typeof AiCopilotRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  CampaignsRoute: typeof CampaignsRoute
  CartsRoute: typeof CartsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ExperimentsRoute: typeof ExperimentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PoliciesRoute: typeof PoliciesRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RevenueRecoveryRoute: typeof RevenueRecoveryRoute
  SettingsRoute: typeof SettingsRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrderSuccessRoute: typeof ShopOrderSuccessRoute
  ShopSearchRoute: typeof ShopSearchRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-activity': {
      id: '/agent-activity'
      path: '/agent-activity'
      fullPath: '/agent-activity'
      preLoaderRoute: typeof AgentActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carts': {
      id: '/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-recovery': {
      id: '/revenue-recovery'
      path: '/revenue-recovery'
      fullPath: '/revenue-recovery'
      preLoaderRoute: typeof RevenueRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/order-success': {
      id: '/shop/order-success'
      path: '/shop/order-success'
      fullPath: '/shop/order-success'
      preLoaderRoute: typeof ShopOrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/shop/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/shop/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentActivityRoute: AgentActivityRoute,
  AiCopilotRoute: AiCopilotRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  CampaignsRoute: CampaignsRoute,
  CartsRoute: CartsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ExperimentsRoute: ExperimentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PoliciesRoute: PoliciesRoute,
  RecommendationsRoute: RecommendationsRoute,
  RevenueRecoveryRoute: RevenueRecoveryRoute,
  SettingsRoute: SettingsRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrderSuccessRoute: ShopOrderSuccessRoute,
  ShopSearchRoute: ShopSearchRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
